/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UiWinMain.java
 *
 * Created on 22.06.2011, 15:02:24
 */
package my.pdfvch;

/**
 *
 * @author ssh
 */
import java.awt.AWTException;
import java.awt.event.AdjustmentEvent;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.pdf.PdfReader;
import com.itextpdf.text.pdf.PdfContentByte;
import com.itextpdf.text.pdf.PdfImportedPage;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import com.itextpdf.text.Rectangle;
import com.itextpdf.text.pdf.AcroFields;
import com.itextpdf.text.pdf.PRStream;
import com.itextpdf.text.pdf.PdfAppearance;
import com.itextpdf.text.pdf.PdfArray;
import com.itextpdf.text.pdf.PdfCopy.PageStamp;
import com.itextpdf.text.pdf.PdfDictionary;
import com.itextpdf.text.pdf.PdfFormField;
import com.itextpdf.text.pdf.PdfIndirectReference;
import com.itextpdf.text.pdf.PdfName;
import com.itextpdf.text.pdf.PdfNumber;
import com.itextpdf.text.pdf.PdfObject;
import com.itextpdf.text.pdf.PdfStamper;
import com.itextpdf.text.pdf.PdfStream;
import java.awt.event.AdjustmentListener;
import javax.swing.text.DefaultCaret;
import javax.swing.JScrollPane;
import java.awt.Robot;
import java.io.FileInputStream;
import java.io.InputStream;


public class UiWinMain extends javax.swing.JFrame {

    /** Creates new form UiWinMain */
    public UiWinMain() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(204, 204, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(" Настройки "));

        jLabel1.setText("Путь к PDF:");

        jTextField1.setText("C:\\pdfs");

        jLabel2.setText("Версия:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1.2", "1.3", "1.4", "1.5", "1.7" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jCheckBox1.setForeground(new java.awt.Color(255, 0, 51));
        jCheckBox1.setText("удалять оригинал (!очень опасно!)");

        jCheckBox2.setSelected(true);
        jCheckBox2.setText("Преобразовать аннотации в картинки");

        jCheckBox3.setText("рекурсивный поиск");
        jCheckBox3.setEnabled(false);

        jCheckBox4.setSelected(true);
        jCheckBox4.setText("PDFX/A Совместимость");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCheckBox4)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jCheckBox3, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                            .addContainerGap())
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jCheckBox1)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jCheckBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(93, 93, 93)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCheckBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jButton1.setText("Запуск");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(" Вывод "));

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setAutoscrolls(true);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel3.setText("Всего файлов:");

        jLabel4.setText("0");

        jLabel5.setText("В обработке:");

        jLabel6.setText("0 из 0");

        jLabel7.setText("Текущий файл:");

        jLabel8.setText("naf");

        jLabel9.setText("Действие: ");

        jLabel10.setText("ожидание запуска");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jButton2.setText("Выход");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(123, 123, 123)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void rep(){
    jLabel4.repaint();
    jLabel4.revalidate();
    jLabel4.paintImmediately(Math.round(jLabel4.getAlignmentX()) , Math.round(jLabel4.getAlignmentY()), jLabel4.getWidth(), jLabel4.getHeight());
    jLabel8.repaint();
    jLabel8.revalidate();
    jLabel8.paintImmediately(Math.round(jLabel8.getAlignmentX()) , Math.round(jLabel8.getAlignmentY()), jLabel8.getWidth(), jLabel8.getHeight());
    jLabel10.repaint();
    jLabel10.revalidate();
    jLabel10.paintImmediately(Math.round(jLabel10.getAlignmentX()) , Math.round(jLabel10.getAlignmentY()), jLabel10.getWidth(), jLabel10.getHeight());
    jLabel6.repaint();
    jLabel6.revalidate();
    jLabel6.paintImmediately(Math.round(jLabel6.getAlignmentX()) , Math.round(jLabel6.getAlignmentY()), jLabel6.getWidth(), jLabel6.getHeight());
}
    
private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    jTextArea1.append("Понеслось... \r\n");
      jLabel10.setText("обработка запущена"); 
     this.rep();
    jScrollPane1.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
      jTextArea1.setCaretPosition( jTextArea1.getDocument().getLength());
   jTextArea1.update(jTextArea1.getGraphics());
   jScrollPane1.getVerticalScrollBar().addAdjustmentListener(new AdjustmentListener() {

            @Override
            public void adjustmentValueChanged(AdjustmentEvent e) {
           e.getAdjustable().setValue(e.getAdjustable().getMaximum());  
            }
        });
   jScrollPane1.update(jScrollPane1.getGraphics());
    String path = jTextField1.getText();
    path = path.replaceAll("\\\\", "/");
      jLabel10.setText("преобразование пути"); 
    this.rep();
      
    jTextField1.setText(path);
    File folder = new File (path);
   
    
    File[] listOfFile = folder.listFiles(new PDFFilter());
    jTextArea1.append("В каталоге  " + path + " нашли " + listOfFile.length + " файлов PDF.\r\n");
    jLabel4.setText(Integer.toString(listOfFile.length) );
    this.rep();
    if (jCheckBox2.isSelected()){
        jLabel10.setText("обработка аннотаций"); 
        this.rep();
    // обработка аннотаций
    for (int i = 0; i < listOfFile.length; i++) {
        jLabel6.setText(Integer.toString(i+1) + " из " + Integer.toString(listOfFile.length));
        jLabel8.setText(listOfFile[i].getName());
        this.rep();
        File document = listOfFile[i];
        File document_out = new File (listOfFile[i].toString()+".flatten");
         byte[] buffer = new byte[(int) document.length()];
                try {
                    InputStream in = new FileInputStream(document);
                    try {
                        in.read(buffer);
                           in.close(); 
                       PdfReader reader = new PdfReader(buffer);
			PdfDictionary pageDict;
			int n = reader.getNumberOfPages();
                      PdfStamper stamper = new PdfStamper(reader, new FileOutputStream(
                                             document_out));
                    
                                     stamper.setFreeTextFlattening(true);
                                     stamper.setFormFlattening(true);                           
                                    
                                     stamper.close();
                                     
                    } catch (DocumentException ex) {
                        Logger.getLogger(UiWinMain.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (IOException ex) {
                        Logger.getLogger(UiWinMain.class.getName()).log(Level.SEVERE, null, ex);
                    }
              
                        
                        
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(UiWinMain.class.getName()).log(Level.SEVERE, null, ex);
                }
                  
    }
    
    
    listOfFile = folder.listFiles(new FlattenFilter());
    }
    jLabel10.setText("начало пережатия"); 
      jTextArea1.setCaretPosition( jTextArea1.getDocument().getLength());
   jTextArea1.update(jTextArea1.getGraphics());
jScrollPane1.update(jScrollPane1.getGraphics());
  this.rep();
     for (int i = 0; i < listOfFile.length; i++) {
         jLabel10.setText("пережимаю..."); 
          jLabel6.setText(Integer.toString(i+1) + " из " + Integer.toString(listOfFile.length));
        jLabel8.setText(listOfFile[i].getName());
          this.rep();
      jTextArea1.append("Обрабатываем " + listOfFile[i] + "...\r\n");
            jTextArea1.setCaretPosition( jTextArea1.getDocument().getLength());
   jTextArea1.update(jTextArea1.getGraphics());
jScrollPane1.update(jScrollPane1.getGraphics());
jTextArea1.requestFocus();
 Robot robot;
            try {
                robot = new Robot();
                robot.keyPress(java.awt.event.KeyEvent.VK_CONTROL);
 robot.keyPress(java.awt.event.KeyEvent.VK_END);
 robot.keyRelease(java.awt.event.KeyEvent.VK_END);
 robot.keyRelease(java.awt.event.KeyEvent.VK_CONTROL);

            } catch (AWTException ex) {
                Logger.getLogger(UiWinMain.class.getName()).log(Level.SEVERE, null, ex);
            }
 
            try {
                PdfReader reader = new PdfReader(listOfFile[i].toString());
                jTextArea1.append("Версия PDF у файла: 1." + reader.getPdfVersion() + "\r\n");
                jTextArea1.setCaretPosition( jTextArea1.getDocument().getLength());
              jTextArea1.update(jTextArea1.getGraphics());
               jScrollPane1.update(jScrollPane1.getGraphics());
                if (!jComboBox1.getSelectedItem().toString().equals("1."+reader.getPdfVersion())){
                // вливаем файл во врайтер и конвертим
                  try {
                     int num = reader.getNumberOfPages();
                     
                     
                         Rectangle pageSize = reader.getPageSize((num > 3) ? 3 : 1);                                        
                     
                  
                  
                     
                      Rectangle newSize = new Rectangle(pageSize.getWidth(), pageSize.getHeight());
            
                      Rectangle unitSize = new Rectangle(pageSize.getWidth(), pageSize.getHeight());
                     Document document = new Document(newSize, 0, 0, 0, 0);
                    try {
                        File dest;
                        if (jCheckBox2.isSelected()){
                         dest = new File(listOfFile[i].toString().replaceAll(".flatten",  "_v_.PDF" ));
                        }else{
                            String pah = listOfFile[i].getAbsolutePath();
                            String fns = listOfFile[i].getName().replaceAll(".pdf",  "" )+"_v_.pdf";
                        dest = new File(pah.substring(0,pah.lastIndexOf(File.separator))+File.separator+fns);
                        }
                        
                        PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream(dest));
                        Character ch = jComboBox1.getSelectedItem().toString().charAt(jComboBox1.getSelectedItem().toString().length()-1);
                        String mycode = ch.toString();
                        jLabel10.setText("сохраняю");
                          this.rep();
                          jTextArea1.append("Конверчу версию в " + jComboBox1.getSelectedItem().toString() + "\r\n");
                              jTextArea1.setCaretPosition( jTextArea1.getDocument().getLength());
   jTextArea1.update(jTextArea1.getGraphics());

                       int myi = Integer.parseInt(mycode);
                        switch (myi){
                            case 2:
                                writer.setPdfVersion(PdfWriter.VERSION_1_2);
                                break;
                        case 4:
                                writer.setPdfVersion(PdfWriter.VERSION_1_4);
                                break;
                            case 3:
                                writer.setPdfVersion(PdfWriter.VERSION_1_3);
                                break;
                                   case 5:
                                writer.setPdfVersion(PdfWriter.VERSION_1_5);
                                break;
                                            case 7:
                                writer.setPdfVersion(PdfWriter.VERSION_1_7);
                                break;
                            default:
                                writer.setPdfVersion(PdfWriter.VERSION_1_4);
                                break;
                        }
                        if (jCheckBox4.isSelected()){
                         writer.setPDFXConformance(PdfWriter.PDFX1A2001);
                        }
                         document.open();
                        PdfContentByte cb = writer.getDirectContent(); 
                         PdfImportedPage page;
                         Rectangle currentSize;
                          float offsetX, offsetY, factor;
                          int total = reader.getNumberOfPages();
                       for (int j = 0; j < total; ) {  
                             if (j < total){
                            currentSize = reader.getPageSize(++j);  
                             }else{
                             currentSize = reader.getPageSize(--j);  
                             }
                            document.setPageSize(currentSize);
                            document.newPage();
                             page = writer.getImportedPage(reader, j);
                          
                             cb.addTemplate(page, 0, 0);
      
                        }
                        document.close();
                        reader.close();
                        jTextArea1.append("Готов файл \r\n");
                          jTextArea1.repaint();                         
                          this.repaint();
                        this.rep();
                    } catch (DocumentException ex) {
                        Logger.getLogger(UiWinMain.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    }catch (java.lang.NullPointerException e){
                        continue;
                  }
                      if (jCheckBox1.isSelected()){
                          if (listOfFile[i].getName().endsWith(".flatten")){
                              File origin = new File (listOfFile[i].getAbsoluteFile().toString().replaceAll(".flatten", ""));
                              origin.delete();
                              listOfFile[i].delete();
                          }else{
                              listOfFile[i].delete();
                          }
                        
                        }
                }
            } catch (IOException ex) {
                Logger.getLogger(UiWinMain.class.getName()).log(Level.SEVERE, null, ex);
            }
          
        
    }
     jTextArea1.append("------ \r\n");
     jTextArea1.append("Все сделано \r\n");
     jLabel10.setText("все операции завершены"); 
     jLabel8.setText("naf"); 
       this.rep();
                          jTextArea1.repaint();                         
                          this.repaint();
                     
}//GEN-LAST:event_jButton1ActionPerformed

private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jComboBox1ActionPerformed


	

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
System.exit(0);
}//GEN-LAST:event_jButton2ActionPerformed

private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
// TODO add your handling code here:
   this.setTitle("PDF-Version-changer 0.7(b)"); 
}//GEN-LAST:event_formWindowOpened

   


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UiWinMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UiWinMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UiWinMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UiWinMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new UiWinMain().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
